@startuml ""
' http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuUBISCiiAYvHA2rEJKuiJjNaqd3Coo_9I2s2YoWa5YjeX3eRQN91HHH2dOtXR0sVnEAIc3nanQ7E9bnS3gbvAI3p0G00
skinparam TextAlign center
skinparam actorStyle awesome

actor Administrador as adm
actor P.O as po
actor Desenvolvedor as dev

package "Gerenciar Tenants" {
  usecase "Criar\nTenant" as createTenant
  usecase "Atualizar\nTenant" as updateTenant
  usecase "Excluir\nTenant" as deleteTenant
}

package "Gerenciar Contas" {
  usecase "Criar\nConta" as createAccount
  usecase "Atualizar\nConta" as updateAccount
  usecase "Alterar\nSenha" as updatePassword
  usecase "Alterar foto\ndo perfil" as updateProfileImage
  usecase "Excluir\nConta" as deleteAccount
}

package "Gerenciar Membros" {
  usecase "Convidar\nMembro" as inviteMember
  usecase "Remover\nMembro" as removeMember
  usecase "Atribuir\nPermissão" as setPermission
}

package "Gerenciar Workspaces" {
  usecase "Criar\nWorkspace" as createWorkspace
  usecase "Atualizar\nWorkspace" as updateWorkspace
  usecase "Excluir\nWorkspace" as deleteWorkspace
}

package "Gerenciar Projetos" {
  usecase "Criar\nProjeto" as createProject
  usecase "Atualizar\nProjeto" as updateProject
  usecase "Excluir\nProjeto" as deleteProject
}

package "Gerenciar Epics" {
  usecase "Criar\nEpic" as createEpic
  usecase "Atualizar\nEpic" as updateEpic
  usecase "Excluir\nEpic" as deleteEpic
}

package "Gerenciar Stories" {
  usecase "Criar\nStory" as createStory
  usecase "Atualizar\nStory" as updateStory
  usecase "Excluir\nStory" as deleteStory
}

package "Gerenciar Tarefas" {
  usecase "Criar\nTarefa" as createTask
  usecase "Atualizar\nTarefa" as updateTask
  usecase "Excluir\nTarefa" as deleteTask
}

package "Gerenciar Sprints" {
  usecase "Criar\nSprint" as createSprint
  usecase "Iniciar\nSprint" as openSprint
  usecase "Fechar\nSprint" as closeSprint
  usecase "Excluir\nSprint" as deleteSprint
}

'Quando concluir todas tarefas de um recurso, deve automaticamente concluir o Recurso, e quando concluir todos os recursos de Epic, deve concluir o Epi
'Criar um grafico de gantt baseado nas tarefas

@enduml
